### PR TITLE
Backend/User

### PR DESCRIPTION
**Pull request by Eric-1120**
User class has been basically set up, including those instance variables that could be used by other methods in other classes. The table of users' information has its columns setup already, and should be able to store user information in the data base.

### CODE REVIEW

**Comment by Archivec2** [comment]
Merged Backend/SocialMediaProfile + Backend/Blocks -> Backend/StudentProfile -> Backend/User as they form integral parts of user related usecases. Completed most of user registration process (including student profile creation and timetable upload and processing). Includes loading courses from data fetched from UofT Timetable builder for testing purposes.

In the actualy build of the application the courses should be loaded only once at the beginning of startup. There are 7603 of them and the current code filters and loads only courses matching CSC207 to speed up the process. (because we all have that course, when we upload the timetable we'll always get a match for that course with respect to the course data in the database, so we can actually test.)

**Comment by Eric-1120** [comment]
Models related to StudentProfile and Block are merged into Backend/User by Alan, which raised a few issues such as the getter and setter methods for the instance variable StudentProfile in the User Entity class was commented out by me when I wrote the code, and they should be implemented now since StudentProfile Entity class has been imported and we can make some update after looking at the documentation of the StudentProfile Entity.
Another issue that concerns me is that some of the user information in the repository did not update when I called the controller method to log a user in. I'm looking forward to having a discussion on this during this week's tutorial.

**Review by Archivec2 — DISMISSED** [review]
existing tests look good, but seems to still miss some cases

**Review by hzc011213 — COMMENTED** [review]
All test passes!

**Review by hzc011213 — DISMISSED** [review]
I walk through most parts of the design, and the test passed.
I did also participate in this pull request and checked and tested all the APIs.

**Comment by hzc011213** [comment]
Backend/Requests and Backend/User-Request has been successfully merged into the Backend/User and all models are up to date.

**Review by hzelg — DISMISSED** [review]
I reviewed most of the frontend integration part, codes are clean, the designs are consistent, and data schemas are well set up. Well done!

**Review by hzelg — COMMENTED** [review]
I reviewed most of the frontend integration part, codes are clean, the designs are consistent, and data schemas are well set up. Well done! Please also add missing test cases, and refactor some frontend files (e.g files in temp)

**Pull request merged**
