### PR TITLE
Merging of Frontend and Backend

### PR DESCRIPTION
**Pull request by Archivec2**
Merge all Entity-Repository-Service-Controller implementations from Backend with all UI implementations from the frontend

### CODE REVIEW

**Review by hzc011213 — DISMISSED** [review]
Passed all Controller Integration Tests, implementing all features we plan to have in our blueprint. 

Potential update in the future:
- Add docstring to frontend codes.
- Apply the matching algorithm using the Strategy design pattern. And allow diverse matching strategies.
- Maybe add @Author

**Review by Eric-1120 — DISMISSED** [review]
Everything for User entity, UserService, UserController, login and register panel in the frontend are ready to merge, a thorough suite of tests are made using the frontend UI, java documentations are added. All good to merge.

**Comment by Eric-1120** [comment]
We can add an email validator to this project in the future, which allows us to verify an email when a user registers an account, and we can also send a verification email to them when they forget the password. This will involve some functionalities that Spring Security provides, hence would need to add that into our configuration.

**Comment by Archivec2** [comment]
All tests are passed, however backend and frontend are still not fully integrated as there were changes in the backend made in later stage, and changes in the frontend not reflected in the backend. Frontend code can do some refactoring for better formatting and also add documentations. We can work on this following this pull request, but individual components of the frontend and backend are functional.

**Comment by IanQuan** [comment]
Individual components of the backend and frontend are functional, but the integration between backend and frontend is not completed yet. Documentations could be added for each pull request before merging.
Possible updates in the future:
-add comments or docstrings for effective code review
-refactor and reformat the frontend code to reduce smell code

**Review by hzelg — COMMENTED** [review]
All tests are passed, and  both frontend and backend file directories are clear. 
Planned update: 
- HabitTest currently only test on creating not updating, need to add validation logic and related UI. 
- Tests are mostly integrated, though called in order and there are many overlaps. Breakdown to smaller tests may be helpful in identifying use case issues.
- Comments of clean architecture to enhance readability.

**Review by Eric-1120 — APPROVED** [review]
More tests are added as I see. Merging progress should be pretty well done.

**Review by hzelg — APPROVED** [review]
Tests are added, issues fixed for request. Well done!

**Review by hzc011213 — APPROVED** [review]
Fixed git test errors, frontend and backend are integrated successfully. 
We may need to make some changes to the registration page to accommodate the formatting of other front-end components.

**Pull request merged**
